### ISSUE TITLE
plugin does not replace image thumbnails

### ISSUE THREAD

**Issue by Zodiac1978** [mansj/enable-media-replace#10]
This is a really great plugin, but there is one little thing I am missing.

If you replace an image with a new filename, the plugin just search&replaces the original filename, but not the thumbnail images in the post content.

**Comment by mansj** [comment]
Yes, this is by design. See https://wordpress.org/support/topic/not-updating-img-src-for-resized-images for an explanation.

**Comment by Zodiac1978** [comment]
Thank you very much for the link and the given explanation. What do you think about the post below your post:
https://wordpress.org/support/topic/not-updating-img-src-for-resized-images?replies=4#post-5687758

Could this be a solution?
