### ISSUE TITLE
chmod() warning

### ISSUE THREAD

**Issue by eugenealegiojo** [mansj/enable-media-replace#11]
I received a warning when I tried to 'Replace the file, use new file name and update all links'. Here is the exact warning message:

Warning: chmod(): No such file or directory in /xx/xx/public_html/wp-content/plugins/enable-media-replace/upload.php on line 125

Which results to another warning 'headers already sent' and unable to continue the process.

Do you know how to fix this?
I tried to chmod the parent directory but still no luck. For the meantime I added a temporary fix by adding '@' before 'chmod' just to disable the warning message.

Please let me know if you have the fix. Thanks.

**Comment by mansj** [comment]
This would mean that your file is no longer residing in the location WordPress thinks it is - i.e. it has been moved after upload. The location is stored in the database, and if chmod() does not work, it's because it's attempting to chmod a file in the location the database claims it is in.
