### ISSUE TITLE
submit enable media replace into wordpress core

### ISSUE THREAD

**Issue by sireneweb** [mansj/enable-media-replace#14]
Hello,
thanks for your great plugin, i'm wondering if you're interesting to submit your plugin into wordpress core ?

https://make.wordpress.org/core/2015/01/13/feature-plugins-in-4-2-and-beyond/

i think it's a part of piece who need to be intrgrate into the core :)

**Comment by mansj** [comment]
Thank you, good idea. I have submitted it.
