### ISSUE TITLE
Language files in root folder

### ISSUE THREAD

**Issue by pedro-mendonca** [mansj/enable-media-replace#9]
Hi,

In github this is ok but in wordpress plugin repository you have language files in the plugin root folder and in language folder (duplicate).
I'm using my language file (pt_PT) that I've just pulled here and it works fine, so I believe the correct place is the language folder.
https://github.com/mansj/enable-media-replace/pull/8

Please check on this.
Thanks

**Comment by mansj** [comment]
Thank you for noticing this, I will update the plugin.
